---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  ca.crt: {{ .Values.elastic.crt | b64enc }}
  elastic.user: {{ .Values.elastic.user | b64enc  }}
  elastic.password: {{ .Values.elastic.password | b64enc }}
  tower.user: {{ .Values.tower.user | b64enc  }}
  tower.password: {{ .Values.tower.password | b64enc }}
